# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a40573a8784c60fcb654c36fad281b9c9050e08c08934260861284dcca9e0c139d395a7a66e29dd3d370ea5cc4c97834a7f89d480263920019a425931761749

test:
  secret_key_base: f457a552068717407156c55933355eddf18cd87bb3a78c1f12d72625a8b74846766b5a36bf95b57cf10f37fc02ea5f2c4d6798cf0aeadf29718554e7f3b4bc3b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
