# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 632b67f317b91704f83b565f60f43286e04b5cdae81575106a5be0e2a41928bf8fb5000bd2d5d30a189d595f21382ccec14ff213a4b689d520b217a53b8eacdb

test:
  secret_key_base: be4632050d0a17f9e14f5668ae4da55348e427fce3f78e70f9ab878ecfac6e97ad0a74de87fa7ef397bd4faac1f2f3ce1fa53a52948bf6dc8a28cdff9d66cf11

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
